### ISSUE TITLE
java.lang.NoClassDefFoundError: com.paypal.android.sdk.bd

### ISSUE THREAD

**Issue by praveenb** [paypal/PayPal-Android-SDK#90]
Hi Guys,

Im getting this error while running the sample code and app crashing at the starting screen itself.

```
 Process: com.paypal.example.paypalandroidsdkexample, PID: 15992
 java.lang.NoClassDefFoundError: com.paypal.android.sdk.bd
 	at com.paypal.android.sdk.ad.a(Unknown Source)
 	at com.paypal.android.sdk.I.run(Unknown Source)
```

I haven't change any code in given SampleApp. Someone please let me know  how to fix this issue.

Thank you.

**Comment by ChenShiChao** [comment]
please help me .

01-05 13:42:57.685: E/AndroidRuntime(29342): java.lang.ExceptionInInitializerError
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at java.lang.Class.newInstanceImpl(Native Method)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at java.lang.Class.newInstance(Class.java:1409)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1565)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.ActivityThread.access$1500(ActivityThread.java:117)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.os.Looper.loop(Looper.java:130)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at android.app.ActivityThread.main(ActivityThread.java:3691)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at java.lang.reflect.Method.invoke(Method.java:507)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at dalvik.system.NativeStart.main(Native Method)
01-05 13:42:57.685: E/AndroidRuntime(29342): Caused by: java.lang.NoClassDefFoundError: com.paypal.android.sdk.payments.PayPalConfiguration
01-05 13:42:57.685: E/AndroidRuntime(29342): 	at com.paypal.example.paypalandroidsdkexample.SampleActivity.<clinit>(SampleActivity.java:58)
01-05 13:42:57.685: E/AndroidRuntime(29342): 	... 15 more

**Comment by braebot** [comment]
How are you installing your app?  If you are using Eclipse, try using Android Studio or Gradle from the command line, and see if that fixes the problem.

**Comment by AndresLpzFdz** [comment]
Hi!
I have been developing my app for months and now I started with the Paypal payment integration. I have the same issue and I´m using Eclipse (and I would like to keep using Eclipse....).

Like other developers, SDK-2.3.5 it´s OK but from 2.4.0 and higher I have this issue.
I´m using ADT v22.2.1 with Elclipse v4.2.1.
I´m testing in a 2.3.6 Android version device (I will check in a 4.x).

Thanks!

**Comment by braebot** [comment]
Thanks for the debug info.  We'll try to reproduce the issue.  Please let us know if the issue is reproducible in a 4.x device.

**Comment by jminht** [comment]
![qq 20150108154515](https://cloud.githubusercontent.com/assets/4132186/5659476/b71151ac-974d-11e4-8746-1898fc96d5f7.png)
@braebot 
here is my screenshot from eclipse and the sample version is Release 2.8.4.

**Comment by huyongjiu** [comment]
Hi, @braebot,

**Comment by huyongjiu** [comment]
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx 
trouble processing:
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/paypal/android/sdk/aC.class
...while processing com/paypal/android/sdk/aC.class
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx 
trouble processing:
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/paypal/android/sdk/aD.class
...while processing com/paypal/android/sdk/aD.class
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx 
trouble processing:
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing com/paypal/android/sdk/aE.class
...while processing com/paypal/android/sdk/aE.class
[2015-03-02 16:24:41 - SlotsTitanswayPaypal] Dx

Hi @braebot, please look at the log above, I found the NoClassDefFoundError issue, because the the PayPalAndroidSDK-2.8.7.jar was built with java se 7 or higher, but android sdk suppot java se 5 or 6, so my adt couldn't compile the jar into my apk libs, I saw the paypal jar file in the bin/dexedLibs/PayPalAndroidSDK-2.8.7-c2e953db57079e6cc73ffb65b5bc73c9.jar only 1k, so the NoClassDefFoundError is throwed. I must use the ADT, so please provide the paypalsdk.jar compiled by java 6 anap, thanks.

**Comment by braebot** [comment]
I'll address the last comment in #147.

**Comment by fred1218zh** [comment]
@braebot Hello, could you help me on NoClassDefFoundError.
I'm using paypal-android-sdk-2.12.4. And it works well on Android 5.0, but causing NoClassDefFoundError on Android 4.4.

Here is the log from Logcat with errors.

12-12 16:17:36.996 27102-27150/com.artloupe E/dalvikvm: Could not find class 'com.paypal.android.sdk.payments.bj', referenced from method com.paypal.android.sdk.payments.PayPalConfiguration.<clinit>
12-12 16:17:36.996 27102-27150/com.artloupe W/dalvikvm: VFY: unable to resolve new-instance 9684 (Lcom/paypal/android/sdk/payments/bj;) in Lcom/paypal/android/sdk/payments/PayPalConfiguration;
12-12 16:17:36.996 27102-27150/com.artloupe D/dalvikvm: VFY: replacing opcode 0x22 at 0x0008
12-12 16:17:37.006 27102-27150/com.artloupe D/dalvikvm: DexOpt: unable to opt direct call 0xf06c at 0x0a in Lcom/paypal/android/sdk/payments/PayPalConfiguration;.<clinit>
12-12 16:17:37.011 27102-27150/com.artloupe W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/paypal/android/sdk/payments/PayPalConfiguration;
12-12 16:17:37.011 27102-27150/com.artloupe W/dalvikvm: threadid=18: thread exiting with uncaught exception (group=0x417ddc08)
12-12 16:17:37.011 27102-27150/com.artloupe E/AndroidRuntime: FATAL EXCEPTION: Thread-2565
                                                              Process: com.artloupe, PID: 27102
                                                              java.lang.NoClassDefFoundError: com.paypal.android.sdk.payments.bj
                                                                  at com.paypal.android.sdk.payments.PayPalConfiguration.<clinit>(Unknown Source)
                                                                  at com.artloupe.payment.PaypalService.initPaymentService(PaypalService.java:20)
                                                                  at com.artloupe.ui.page.SplashActivity$1.run(SplashActivity.java:41)
                                                                  at java.lang.Thread.run(Thread.java:841)


thanks.

**Comment by vinayakb73** [comment]
Hi everyone,
I also have this problem. this problem not in Lollipop(>api21) but only in Api less than 21.. I am using Android studio 1.5.1 and java 1.8. I am also including my gradle dependencies below.. please help me

dependencies {
compile fileTree(include: ['*.jar'], dir: 'libs')
testCompile 'junit:junit:4.12'
compile project(':linkedin-sdk')
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:design:23.1.1'
compile 'com.android.support:cardview-v7:23.1.1'
compile('com.facebook.android:facebook-android-sdk:4.8.1') {
exclude module: 'support-v4'
}
compile 'com.google.android.gms:play-services:8.4.0'
compile 'com.google.android.gms:play-services-auth:8.4.0'
compile 'com.android.support:multidex:1.0.1'
compile 'com.paypal.sdk:paypal-android-sdk:2.13.0'
compile 'com.stripe:stripe-android:+'

}

**Comment by ashishraval21** [comment]
![multidex](https://cloud.githubusercontent.com/assets/11411880/12637760/ca89a8c0-c5bd-11e5-86d5-87d06dc2bcd1.png)


Try this . it may be working for you :)

**Comment by vinayakb73** [comment]
Thanks ashishraval21, It works...

**Comment by braebot** [comment]
Closing as I don't believe there's anything we can do on the SDK side to fix multidex issues.

**Comment by ashishraval21** [comment]
You are nothing to do in your SDK but you have to guideline to your clients to add things about multidex in there application so they are never got this type of issue in this case. which are mostly occured on Android os version less than 5.

**Comment by gkfillipus** [comment]
Hello everyone i am also getting the same error after added the paypay sdk its causing the app crashing. please help

**Comment by gkfillipus** [comment]
See bellow

02-29 06:51:23.000 995-995/? E/AndroidRuntime: FATAL EXCEPTION: main
02-29 06:51:23.000 995-995/? E/AndroidRuntime: Process: com.kupapataApp, PID: 995
02-29 06:51:23.000 995-995/? E/AndroidRuntime: java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzmp
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at com.google.android.gms.measurement.internal.zzz.zzj(Unknown Source)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at com.google.android.gms.measurement.internal.zzv.<init>(Unknown Source)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at com.google.android.gms.measurement.internal.zzz.zzAq(Unknown Source)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at com.google.android.gms.measurement.internal.zzv.zzaL(Unknown Source)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1656)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1627)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.app.ActivityThread.installProvider(ActivityThread.java:5015)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4589)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110)
02-29 06:51:23.000 995-995/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)

**Comment by braebot** [comment]
@gkfillipus, according to [this SO post](http://stackoverflow.com/questions/33161671/java-lang-noclassdeffounderror-com-google-android-gms-internal-zzmp), this issue is related to multidex.  Please follow the accepted answer's suggestion, which should fix the answer.

**Comment by gkfillipus** [comment]
Hi tasnk you for quick response. I did that but nothing helped the app still crashing

**Comment by alalastephen** [comment]
I am still getting the same error and I am not using Multidex. Please reopen the issue. It is not solved.

**Comment by braebot** [comment]
@alalastephen, does it occur on all devices, or only 4.x?
